-- AlterTable
ALTER TABLE `production` MODIFY `lot` VARCHAR(200) NULL,
    MODIFY `reference` VARCHAR(200) NULL,
    MODIFY `reference_sorea` VARCHAR(200) NULL,
    MODIFY `reference_eai` VARCHAR(200) NULL,
    MODIFY `status_of` VARCHAR(200) NULL,
    MODIFY `flux` VARCHAR(200) NULL,
    MODIFY `date_de_commande` VARCHAR(200) NULL,
    MODIFY `qte_bdee` VARCHAR(200) NULL,
    MODIFY `ecr_brut` VARCHAR(200) NULL,
    MODIFY `ecr_net` VARCHAR(200) NULL,
    MODIFY `taux_de_rebut` VARCHAR(200) NULL,
    MODIFY `observation_prod` VARCHAR(200) NULL,
    MODIFY `demontage` VARCHAR(200) NULL,
    MODIFY `reste_a_demonter` VARCHAR(200) NULL,
    MODIFY `sous_ensemble` VARCHAR(200) NULL,
    MODIFY `rebut_sous_ens` VARCHAR(200) NULL,
    MODIFY `montage` VARCHAR(200) NULL,
    MODIFY `rebut_montage` VARCHAR(200) NULL,
    MODIFY `rebut_export` VARCHAR(200) NULL,
    MODIFY `reste_a_Exporter` VARCHAR(200) NULL,
    MODIFY `bloquage` VARCHAR(200) NULL,
    MODIFY `zingueur` VARCHAR(200) NULL,
    MODIFY `produit` VARCHAR(200) NULL,
    MODIFY `rebut_total` VARCHAR(200) NULL,
    MODIFY `Export` VARCHAR(200) NULL;
