export type dataProps = {
  OF: string;
  Lot: string;
  Produit: string;
  Référence: string;
  'Référence Sorea': string;
  'Référence EAI': string;
  'Statut Of': string;
  Flux: string;
  'Date De Commande': string;
  'Qté Ddée': string;
  'Qté Reçu': string;
  'Ecr.Brut': string;
  'Ecr.Net': string;
  'Taux De Rebut': string;
  'Observation Prod': string;
  Démontage: string;
  'Reste à démonter': string;
  'Sous-Ensemble': string;
  'Rebut Sous-Ens': string;
  Montage: string;
  'Rebut Montage': string;
  'Rebut Total': string;
  Export: string;
  'Rebut Export': string;
  'Reste à Exporter': number;
  Bloquage: number;
  Zingueur: number;
};
